import type { HashAlgorithm } from "../../types";

export const hashAlgorithms: HashAlgorithm[] = [
  {
    id: "md5",
    label: "MD5",
    category: "Common Hash",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "Fast legacy digest often used to compare non-sensitive files.",
    bestFor: "Checksums for accidental corruption and compatibility with old systems.",
    avoidFor: "Security, signatures, password storage, or collision-resistant workflows.",
    warning: "MD5 is broken for security. Use SHA-256 or stronger for trust decisions.",
  },
  {
    id: "sha1",
    label: "SHA-1",
    category: "SHA Family",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "Legacy SHA digest that remains common in older APIs and Git-like contexts.",
    bestFor: "Compatibility checks where SHA-1 is already required.",
    avoidFor: "New security-sensitive systems.",
    warning: "SHA-1 is no longer collision resistant enough for modern security.",
  },
  {
    id: "sha224",
    label: "SHA-224",
    category: "SHA Family",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "Truncated SHA-2 member with a 224-bit output.",
    bestFor: "Protocols that explicitly require SHA-224.",
    avoidFor: "Password hashing or places where SHA-256 is the standard choice.",
  },
  {
    id: "sha256",
    label: "SHA-256",
    category: "SHA Family",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "Modern general-purpose SHA-2 hash with broad support.",
    bestFor: "File integrity, API signatures with HMAC, dedupe keys, and audit fingerprints.",
    avoidFor: "Direct password storage without a password hashing scheme.",
  },
  {
    id: "sha384",
    label: "SHA-384",
    category: "SHA Family",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "SHA-2 variant commonly paired with high-security protocols.",
    bestFor: "TLS-like ecosystems and longer digest requirements.",
    avoidFor: "Password storage by itself.",
  },
  {
    id: "sha512",
    label: "SHA-512",
    category: "SHA Family",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "SHA-2 variant optimized on many 64-bit platforms.",
    bestFor: "Strong fingerprints, high-throughput systems, and compatibility needs.",
    avoidFor: "Password hashing without salt and work factor.",
  },
  {
    id: "sha512-224",
    label: "SHA-512/224",
    category: "SHA Family",
    available: false,
    outputFormats: ["hexLower", "hexUpper"],
    description: "SHA-512 family variant truncated to 224 bits.",
    bestFor: "Standards that specifically require SHA-512/224.",
    avoidFor: "General web utility use unless interoperability requires it.",
  },
  {
    id: "sha512-256",
    label: "SHA-512/256",
    category: "SHA Family",
    available: false,
    outputFormats: ["hexLower", "hexUpper"],
    description: "SHA-512 family variant truncated to 256 bits.",
    bestFor: "Protocols that require this exact SHA-2 variant.",
    avoidFor: "Password hashing or replacing HMAC configuration.",
  },
  ...([224, 256, 384, 512] as const).map((bits) => ({
    id: `sha3-${bits}`,
    label: `SHA3-${bits}`,
    category: "SHA3 / Keccak" as const,
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"] as const,
    description: `NIST SHA-3 hash with a ${bits}-bit output.`,
    bestFor: "Modern SHA-3 compatibility, fingerprints, and alternate hash-family checks.",
    avoidFor: "Password hashing without a dedicated KDF.",
  })),
  ...([224, 256, 384, 512] as const).map((bits) => ({
    id: `keccak-${bits}`,
    label: `Keccak-${bits}`,
    category: "SHA3 / Keccak" as const,
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"] as const,
    description: `Original Keccak digest with a ${bits}-bit output, used by some blockchain tooling.`,
    bestFor: "Ethereum-adjacent compatibility and systems that name Keccak explicitly.",
    avoidFor: "Replacing SHA3 when a spec says SHA3. Padding differs.",
  })),
  {
    id: "ripemd160",
    label: "RIPEMD-160",
    category: "Common Hash",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "160-bit hash still seen in cryptocurrency and legacy workflows.",
    bestFor: "Compatibility with systems that require RIPEMD-160.",
    avoidFor: "New security designs when SHA-256 or SHA-3 fits.",
  },
  {
    id: "blake2b",
    label: "BLAKE2b",
    category: "Common Hash",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "Fast modern hash designed for 64-bit platforms.",
    bestFor: "High-speed file fingerprints and modern checksum-like use cases.",
    avoidFor: "Password storage by itself.",
  },
  {
    id: "blake2s",
    label: "BLAKE2s",
    category: "Common Hash",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "BLAKE2 variant tuned for smaller and 32-bit environments.",
    bestFor: "Compact environments and fast content hashes.",
    avoidFor: "Password storage by itself.",
  },
  {
    id: "blake3",
    label: "BLAKE3",
    category: "Common Hash",
    available: true,
    outputFormats: ["hexLower", "hexUpper", "base64"],
    description: "Very fast modern hash with extendable output support.",
    bestFor: "Fast local file fingerprints and developer tooling.",
    avoidFor: "Specs that require SHA-2, SHA-3, or bcrypt/Argon2.",
  },
  {
    id: "crc32",
    label: "CRC32",
    category: "Checksum",
    available: true,
    outputFormats: ["hexLower", "hexUpper"],
    description: "Classic checksum for accidental error detection.",
    bestFor: "ZIP-like formats, quick corruption checks, and legacy checksums.",
    avoidFor: "Any adversarial or security-sensitive validation.",
  },
  {
    id: "adler32",
    label: "Adler-32",
    category: "Checksum",
    available: true,
    outputFormats: ["hexLower", "hexUpper"],
    description: "Lightweight checksum used in formats such as zlib.",
    bestFor: "Fast accidental-corruption checks.",
    avoidFor: "Security, identity, or tamper detection.",
  },
];
